"use client";

/**
 * Laqta — the work speaks: actual generated Darija ad videos playing in
 * phone frames, straight out of the pipeline. Falls back to the app
 * screenshot when no pulled videos exist yet.
 */
import { useEffect, useRef } from "react";
import { DeviceFrame } from "@/components/ui/DeviceFrame";
import { useReducedMotionSafe } from "@/lib/hooks";
import { ChipRow, CtaRow, IndexLabel, PanelShell, type PanelProps } from "./shared";

function AdPhone({ src, poster, delay }: { src: string; poster?: string; delay: number }) {
  const reduced = useReducedMotionSafe();
  const ref = useRef<HTMLVideoElement | null>(null);

  useEffect(() => {
    const video = ref.current;
    if (!video || reduced) return;
    const observer = new IntersectionObserver(([entry]) => {
      if (entry.isIntersecting) {
        const t = setTimeout(() => video.play().catch(() => {}), delay);
        return () => clearTimeout(t);
      }
      video.pause();
    });
    observer.observe(video);
    return () => observer.disconnect();
  }, [reduced, delay]);

  return (
    <figure className="overflow-hidden rounded-[1.1rem] border-4 border-black/70 bg-black shadow-2xl">
      {/* Real phone proportions; the ad covers the whole screen (cropped
          rather than letterboxed) like a full-screen reel. */}
      <div className="relative aspect-[390/844]">
        <video
          ref={ref}
          muted
          loop
          playsInline
          preload="none"
          poster={poster}
          className="absolute inset-0 h-full w-full object-cover"
        >
          <source src={src} type="video/mp4" />
        </video>
        <span
          aria-hidden
          className="absolute left-1/2 top-0 z-10 h-[3.1%] w-[38%] -translate-x-1/2 rounded-b-[0.55rem] bg-black"
        />
      </div>
    </figure>
  );
}

export function LaqtaPanel(props: PanelProps) {
  const { project, world, extras } = props;
  const videos = extras?.laqtaVideos ?? [];

  return (
    <PanelShell world={world}>
      <div className="grid items-center gap-12 lg:grid-cols-[5fr_6fr]">
        <div>
          <IndexLabel {...props} />
          <h3
            className="font-display mt-4 font-bold uppercase leading-none"
            style={{ fontSize: "clamp(3rem, 6vw, 5.5rem)", color: world.fg }}
          >
            Laqta
            <span style={{ color: world.link }}>.</span>
          </h3>
          <p
            className="mt-2 font-mono text-[11px] uppercase tracking-[0.3em]"
            style={{ color: world.muted }}
          >
            براند كيت → إعلان فيديو بالدارجة
          </p>
          <p className="mt-5 max-w-md text-lg leading-relaxed" style={{ color: world.body }}>
            {project.tagline}
          </p>
          {videos.length > 0 && (
            <p className="mt-4 max-w-md text-sm" style={{ color: world.muted }}>
              The ads playing here were generated by the pipeline itself — no
              editor touched them.
            </p>
          )}
          <ChipRow project={project} world={world} className="mt-6" max={6} />
          <CtaRow project={project} world={world} className="mt-8" />
        </div>

        {/* The product and its output in one frame: laqta.ma itself, with the
            ads it rendered stacked over the corner. */}
        <div className="relative hidden lg:block">
          <div className="pr-[26%]">
            <DeviceFrame
              src={project.screenshots.desktop[0]}
              alt={project.alt}
              accent={project.accent}
              kind="desktop"
              monogram="L"
              sizes="(min-width: 1024px) 42vw, 90vw"
            />
          </div>
          {videos.length > 0 && (
            <div className="absolute bottom-[-2.5rem] right-0 flex w-[46%] items-end justify-end gap-3">
              {videos.slice(0, 3).map((v, i) => (
                <div
                  key={v.src}
                  className={`w-1/3 ${
                    i === 1 ? "translate-y-6" : i === 2 ? "-translate-y-4" : "translate-y-0"
                  }`}
                >
                  <AdPhone src={v.src} poster={v.poster} delay={i * 400} />
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="flex items-end gap-4 lg:hidden">
          <div className="flex-1">
            <DeviceFrame
              src={project.screenshots.desktop[0]}
              alt={project.alt}
              accent={project.accent}
              kind="desktop"
              monogram="L"
              sizes="60vw"
            />
          </div>
          {videos.length > 0 && (
            <div className="w-[34%] max-w-[140px]">
              <AdPhone src={videos[0].src} poster={videos[0].poster} delay={0} />
            </div>
          )}
        </div>
      </div>
    </PanelShell>
  );
}
