import json

with open("scratch_units.json") as f:
    data = json.load(f)

T = {}

# BUDGET (59 items)
T["budget_0"] = "Budget"
T["budget_1"] = "9.1 V1 — le pilote complet"
T["budget_2"] = "Tous les montants sont en dollars américains, hors TVA. La TVA est ajoutée sur la facture au taux en vigueur."
T["budget_3"] = "Lot"
T["budget_4"] = "Délai"
T["budget_5"] = "Montant, hors TVA"
T["budget_6"] = "A. Mise en place et infrastructure"
T["budget_7"] = "Semaine 1"
T["budget_8"] = "350 $"
T["budget_9"] = "B. Intégration WhatsApp, deux numéros"
T["budget_10"] = "Semaines 2 – 3"
T["budget_11"] = "950 $"
T["budget_12"] = "C. Moteur IA et orchestration"
T["budget_13"] = "Semaines 2 – 3"
T["budget_14"] = "1 050 $"
T["budget_15"] = "D. Backend et modèle de données"
T["budget_16"] = "Semaines 1 – 3"
T["budget_17"] = "1 000 $"
T["budget_18"] = "E. Back-office opérateur"
T["budget_19"] = "Semaine 4"
T["budget_20"] = "950 $"
T["budget_21"] = "F. Tracking QR et attribution"
T["budget_22"] = "Semaine 5"
T["budget_23"] = "250 $"
T["budget_24"] = "G. Livraison et courses"
T["budget_25"] = "Semaine 5"
T["budget_26"] = "350 $"
T["budget_27"] = "H. Tableau de bord KPI, exports, documentation et passation"
T["budget_28"] = "Semaines 6 – 7"
T["budget_29"] = "700 $"
T["budget_30"] = "Total V1, opérationnel en semaine 8"
T["budget_31"] = "8 semaines"
T["budget_32"] = "5 600 $"
T["budget_33"] = "9.2 Phase 2"
T["budget_34"] = "Les quatre fonctionnalités de la section 7.1 sont tarifées à <strong>400 $</strong> lorsqu'elles sont engagées conjointement avec la V1, et livrées au cours du premier mois du pilote dès qu'il y a des données pour les calibrer. Commandées séparément après le pilote, elles sont à <strong>600 $</strong> : le travail est le même, mais ré-ouvrir un projet terminé nécessite de le remobiliser, de le retester et de le redéployer."
T["budget_35"] = "Deux façons de l'envisager"
T["budget_36"] = "Total, hors TVA"
T["budget_37"] = "V1 maintenant, décision sur la phase 2 après le pilote"
T["budget_38"] = "5 600 $ <span class=\"muted\">puis 600 $</span>"
T["budget_39"] = "<b>V1 et phase 2 ensemble</b> — engagement total à la signature"
T["budget_40"] = "<b>6 000 $</b>"
T["budget_41"] = "9.3 Maintenance et support"
T["budget_42"] = "Le premier mois après la mise en production est inclus, sans surcoût — ce mois appartient au lancement, pas à un contrat. À partir du deuxième mois, la maintenance s'élève à 300 $ par mois hors TVA, avec un minimum de trois mois, renouvelable par blocs de trois mois. Trois mois payés d'avance reviennent à 800 $ au lieu de 900 $. Chacun de nous peut décliner un renouvellement à la fin d'un bloc, le système, la documentation et les comptes restant entre vos mains."
T["budget_43"] = "Ce qui est couvert"
T["budget_44"] = "Délai de traitement"
T["budget_45"] = "<b>Quelque chose est en panne</b><br/><span class=\"muted\">messages qui n'arrivent pas, l'IA qui ne répond pas, le back-office indisponible, données non enregistrées</span>"
T["budget_46"] = "Pris en charge sous 3 heures et, une fois la cause identifiée, corrigé et déployé sous 5 heures. Signalements reçus entre 08h00 et 22h00 heure du Maroc, n'importe quel jour de la semaine ; tout incident ultérieur est repris le lendemain matin. Lorsque la défaillance incombe à Meta, 360dialog ou un fournisseur de modèle, vous obtenez le diagnostic et une solution de contournement dans la même fenêtre."
T["budget_47"] = "<b>Surveillance et entretien</b>"
T["budget_48"] = "Continu : surveillance du serveur et des sauvegardes, mises à jour de sécurité, tests de restauration et ajustement des prompts et du comportement de l'IA à mesure que le pilote nous apprend ce que les voyageurs demandent réellement."
T["budget_49"] = "<b>Modifications mineures</b><br/><span class=\"muted\">formulation et prompts, un nouveau champ, une nouvelle colonne de tableau de bord ou un nouvel export, un nouveau modèle de message, une nouvelle catégorie ou un compte opérateur, un filtre ou un seuil</span>"
T["budget_50"] = "Inclus dans le forfait et planifié plutôt que précipité — généralement sous quelques jours ouvrés après la demande. Celles-ci ne tournent pas sur l'horloge des incidents, car une réponse dans l'heure à une modification de formulation n'aide aucun de nous deux."
T["budget_51"] = "<b>Nouvelles fonctionnalités</b><br/><span class=\"muted\">un nouvel écran, une nouvelle intégration, un nouveau service ou canal</span>"
T["budget_52"] = "Dimensionné selon ce que la fonctionnalité est réellement, avec une date et un prix convenus par écrit avant tout démarrage de travaux. Il n'y a pas de compteur d'heures ni de facture surprise."
T["budget_53"] = "9.4 Modalités de paiement"
T["budget_54"] = "<span>À la signature</span><b>40%</b>"
T["budget_55"] = "<span>Lorsque la version de test est opérationnelle sur les numéros de test et que vous pouvez exécuter la boucle complète vous-même, fin de semaine 3</span><b>40%</b>"
T["budget_56"] = "<span>À la mise en production du pilote, contre remise des livrables</span><b>20%</b>"
T["budget_57"] = "Le travail commence dès réception du premier paiement — j'ai de la disponibilité maintenant et aucune file d'attente devant vous — et le planning de huit semaines démarre à cette date."
T["budget_58"] = "Facturé par une société, en dirhams au taux de change à la date de facturation. Les prix s'entendent hors TVA et hors services tiers de la section 11, que vous souscrivez et réglez directement. Un jalon est considéré comme accepté cinq jours ouvrés après la livraison, sauf si vous formulez une remarque par écrit."

# ROI (45 items)
T["roi_0"] = "Ce que le pilote doit générer pour s'amortir"
T["roi_1"] = "Le développement est un forfait unique de 5 600 $. L'exploitation du service coûte ensuite entre 175 $ et 260 $ par mois en services tiers — serveurs, accès WhatsApp, frais de messages, utilisation des modèles — détaillés dans la section 11. La maintenance, si vous la conservez, ajoute 300 $. Le service doit donc couvrir entre 215 $ et 515 $ par mois selon que je reste ou non sous forfait."
T["roi_2"] = "Trois hypothèses transforment cela en un chiffre, et toutes trois sont à remplacer par les vôtres une fois le catalogue négocié : une réservation moyenne de 600 MAD (environ 63 $), une marge plateforme de 15 %, soit environ 9,50 $ par réservation, et un entonnoir où 100 scans produisent environ 70 conversations, 45 demandes et 18 réservations."
T["roi_3"] = "170 $ pour 100 scans"
T["roi_4"] = "Environ 1,70 $ de marge pour chaque voyageur qui scanne un code QR, qu'il réserve ou non. C'est l'unité qui compte, car les scans sont la seule chose que vos partenaires contrôlent."
T["roi_5"] = "54 réservations par mois"
T["roi_6"] = "Moins de deux par jour. C'est le point où le service couvre tout ce qu'il coûte à l'exploitation, maintenance comprise. Sans maintenance, le seuil de rentabilité tombe à 25 réservations par mois, soit moins d'une par jour."
T["roi_7"] = "46 jours pour amortir le développement"
T["roi_8"] = "À 10 scans par jour répartis sur vos dix premiers riads partenaires — un scan par riad tous les deux ou trois jours — la marge cumulée rembourse l'intégralité du développement de 5 600 $ en environ six semaines de pilote en direct."
T["roi_9"] = "Scans / jour"
T["roi_10"] = "Réservations / mois"
T["roi_11"] = "Marge brute / mois"
T["roi_12"] = "Coût d'exploitation mensuel"
T["roi_13"] = "Marge nette / mois"
T["roi_14"] = "Amortissement du développement"
T["roi_15"] = "3"
T["roi_16"] = "16"
T["roi_17"] = "152 $"
T["roi_18"] = "215 $"
T["roi_19"] = "<span class=\"muted\">-63 $</span>"
T["roi_20"] = "Déficitaire"
T["roi_21"] = "5"
T["roi_22"] = "27"
T["roi_23"] = "257 $"
T["roi_24"] = "215 $"
T["roi_25"] = "+42 $"
T["roi_26"] = "133 jours"
T["roi_27"] = "10"
T["roi_28"] = "54"
T["roi_29"] = "513 $"
T["roi_30"] = "515 $ <span class=\"muted\">avec maintien</span>"
T["roi_31"] = "Équilibre"
T["roi_32"] = "46 jours"
T["roi_33"] = "25"
T["roi_34"] = "135"
T["roi_35"] = "1 283 $"
T["roi_36"] = "545 $"
T["roi_37"] = "+738 $"
T["roi_38"] = "18 jours"
T["roi_39"] = "50"
T["roi_40"] = "270"
T["roi_41"] = "2 565 $"
T["roi_42"] = "595 $"
T["roi_43"] = "+1 970 $"
T["roi_44"] = "9 jours"

# RUNNING (43 items)
T["running_0"] = "Ce qu'il en coûte pour fonctionner"
T["running_1"] = "Les chiffres ci-dessous correspondent au volume attendu du pilote — environ 300 demandes par mois, une moyenne de trois fournisseurs sollicités par demande, soit environ 900 messages de modèles sortants. Chaque compte est ouvert à votre nom et vous est facturé directement. La maintenance ne figure pas dans ce tableau : c'est un choix séparé, tarifé à la section 9.3."
T["running_2"] = "Service"
T["running_3"] = "Utilisé pour"
T["running_4"] = "Estimation mensuelle"
T["running_5"] = "<b>Hetzner</b>"
T["running_6"] = "Serveur et stockage de sauvegarde : backend, base de données, back-office et tableau de bord"
T["running_7"] = "15 – 35 $"
T["running_8"] = "<b>360dialog</b>"
T["running_9"] = "Accès à l'API WhatsApp Business, deux numéros, forfait fixe sans majoration sur les frais de Meta"
T["running_10"] = "118 $"
T["running_11"] = "<b>Frais de messagerie Meta</b>"
T["running_12"] = "Messages modèles vers les fournisseurs. Les réponses dans la fenêtre de 24 heures ouverte par un voyageur sont gratuites, et chaque numéro bénéficie d'une allocation mensuelle de 1 000 messages de service gratuits"
T["running_13"] = "25 – 60 $"
T["running_14"] = "<b>APIs LLM</b>"
T["running_15"] = "Extraction, dialogue, interprétation des réponses des fournisseurs — évolue avec les conversations, voir ci-dessous"
T["running_16"] = "15 – 35 $"
T["running_17"] = "<b>Surveillance et e-mails transactionnels</b>"
T["running_18"] = "Alertes, réinitialisations de mot de passe"
T["running_19"] = "0 – 10 $"
T["running_20"] = "<b>Total estimé au volume du pilote</b>"
T["running_21"] = "<b>175 – 260 $</b>"
T["running_22"] = "<strong>Ponctuel et non inclus ci-dessus :</strong> l'enregistrement du domaine (environ 15 $/an) et l'enregistrement initial du numéro chez votre opérateur si vous n'avez pas encore deux cartes SIM marocaines (environ 60 MAD chacune)."
T["running_23"] = "11.1 Comment le coût de l'IA évolue avec l'utilisation"
T["running_24"] = "C'est l'élément qui inquiète le plus souvent les fondateurs, et c'est celui qui surprend le plus en pratique : le coût de l'IA est le poste le plus faible de la facture, et de loin."
T["running_25"] = "Une conversation moyenne de conciergerie consomme environ cinq échanges avec le modèle : un accueil et une clarification, une extraction structurée, un formatage de sollicitation de fournisseur, une interprétation de réponse libre et une présentation d'offre. À travers ces étapes, le système envoie et reçoit environ 4 000 tokens d'entrée et 600 tokens de sortie."
T["running_26"] = "Modèle"
T["running_27"] = "Par 1 000 conversations"
T["running_28"] = "Au volume du pilote (300/mois)"
T["running_29"] = "À 3 000 conversations/mois"
T["running_30"] = "Google Gemini 2.5 Flash"
T["running_31"] = "1,80 $"
T["running_32"] = "0,54 $"
T["running_33"] = "5,40 $"
T["running_34"] = "OpenAI GPT-4o mini"
T["running_35"] = "2,40 $"
T["running_36"] = "0,72 $"
T["running_37"] = "7,20 $"
T["running_38"] = "Anthropic Claude 3.5 Haiku"
T["running_39"] = "4,20 $"
T["running_40"] = "1,26 $"
T["running_41"] = "12,60 $"
T["running_42"] = "Même sur le modèle le plus cher ci-dessus et à un volume dix fois supérieur à celui du pilote, l'ensemble de la facture d'IA s'élève à moins de treize dollars par mois. La ligne de messagerie WhatsApp de Meta sera plus élevée que la facture LLM d'un ordre de grandeur. C'est précisément pour cela que la V1 est conçue avec une couche multi-fournisseurs : vous pouvez exécuter le modèle le plus intelligent là où la nuance linguistique compte et basculer sur un modèle économique en un clic dans le back-office sans redéployer le système."

print(f"Part 4 done: {len(T)} items.")
with open("scripts/i18n_data/part4.json", "w", encoding="utf-8") as f:
    json.dump(T, f, ensure_ascii=False, indent=2)
