import json

with open("scratch_units.json") as f:
    data = json.load(f)

T = {}

# DATA (56 items)
T["data_0"] = "Modèle de données"
T["data_1"] = "Le modèle ci-dessous couvre les sections 6, 7, 9, 10, 12 et 14 de votre cahier des charges et est conçu pour permettre le classement automatisé et les analyses de la phase 2 sans migration destructive."
T["data_2"] = "Entité"
T["data_3"] = "Contenu principal"
T["data_4"] = "Rôle"
T["data_5"] = "<b>Partenaire</b>"
T["data_6"] = "Nom, type (riad, hôtel, boutique), identifiant unique, URL/QR, contact, actif"
T["data_7"] = "Origine des clients et attribution."
T["data_8"] = "<b>Client</b>"
T["data_9"] = "Numéro WhatsApp, prénom (si fourni), langue détectée, partenaire d'origine, date du premier contact"
T["data_10"] = "Fiche client et historique."
T["data_11"] = "<b>Conversation</b>"
T["data_12"] = "Client, mode (IA / humain), opérateur assigné, indicateur « attention requise », horodatages"
T["data_13"] = "Gestion du dialogue et bascule vers l'humain."
T["data_14"] = "<b>Message</b>"
T["data_15"] = "Conversation, direction, contenu, auteur (client, IA, opérateur, système), horodatage"
T["data_16"] = "Historique complet, traçabilité."
T["data_17"] = "<b>Catégorie</b>"
T["data_18"] = "Nom, ordre d'affichage, actif"
T["data_19"] = "Restauration, transport, activités, bien-être, courses."
T["data_20"] = "<b>Fournisseur</b>"
T["data_21"] = "Nom, catégorie(s), zone, standing, fourchette de prix, capacité, horaires, jours de fermeture, contact WhatsApp, langues, délai de réponse cible, commission, notes internes, statut actif"
T["data_22"] = "Catalogue vérifié, 15 champs requis par le cahier des charges."
T["data_23"] = "<b>Service</b>"
T["data_24"] = "Fournisseur, libellé, description, prix indicatif, conditions"
T["data_25"] = "Plusieurs services par fournisseur."
T["data_26"] = "<b>Demande</b>"
T["data_27"] = "Client, conversation, catégorie, critères structurés (date, heure, personnes, budget, zone, préférences), partenaire prescripteur, statut, opérateur, horodatages par statut"
T["data_28"] = "Le pivot central du système. Machine à états, voir 6.2."
T["data_29"] = "<b>Sollicitation fournisseur</b>"
T["data_30"] = "Demande, fournisseur, envoyé le, réponse (disponible, indisponible, partiel), prix, délai, conditions, reçu le, canal (bouton, texte, opérateur)"
T["data_31"] = "Une ligne par fournisseur interrogé. C'est ici que les temps de réponse et les taux de refus sont calculés."
T["data_32"] = "<b>Offre</b>"
T["data_33"] = "Demande, sollicitation(s) retenue(s), soumise au client le, choix du client"
T["data_34"] = "Ce qui a été présenté et ce que le voyageur a choisi."
T["data_35"] = "<b>Transaction</b>"
T["data_36"] = "Demande, fournisseur, prix client, montant fournisseur, marge plateforme, commission partenaire, statut, résultat"
T["data_37"] = "Suivi financier pour information, sans paiement en ligne."
T["data_38"] = "<b>Avance de fonds</b>"
T["data_39"] = "Demande de course, coursier, montant avancé, justificatif (photo ou lien), frais de livraison, montant dû, remboursé (oui/non), horodatages"
T["data_40"] = "Le cas d'usage livraison et courses, section 12."
T["data_41"] = "<b>Opérateur</b>"
T["data_42"] = "Nom, e-mail, rôle (admin, opérateur), actif"
T["data_43"] = "Comptes multiples dès le premier jour."
T["data_44"] = "<b>Configuration IA</b>"
T["data_45"] = "Fournisseur actif, modèle, prompts (accueil, extraction, présentation des offres, relance), langues, version, modifié par"
T["data_46"] = "Prompts modifiables et historisés depuis le back-office."
T["data_47"] = "<b>Journal</b>"
T["data_48"] = "Type d'événement, entité, données, horodatage"
T["data_49"] = "Alimente le tableau de bord et les exports CSV."
T["data_50"] = "6.2 La machine à états des demandes"
T["data_51"] = "Une demande ne peut être que dans un seul état à la fois, et seules les transitions valides sont autorisées. Chaque transition est horodatée, ce qui donne gratuitement les temps de réponse et de traitement."
T["data_52"] = "à traiter"
T["data_53"] = "envoyé"
T["data_54"] = "en attente"
T["data_55"] = "Une conversation suit la même logique avec deux états : <em>IA</em> ou <em>humain</em>. En mode humain, l'IA ne répond jamais. Le retour au mode IA est une action explicite de l'opérateur avec un résumé de contexte généré pour que l'IA reprenne sans redemander au client ce qu'il vient de dire."

# SCOPE (28 items)
T["scope_0"] = "Ce que contient la V1, lot par lot"
T["scope_1"] = "Un point de principe avant le tableau. Les pièces de ce produit dépendent les unes des autres : une demande est inutile sans fournisseur à interroger, les réponses des fournisseurs sont inutiles sans back-office pour les lire, et rien de tout cela ne signifie quoi que ce soit sans attribution et sans exports. La V1 proposée ici couvre les huit lots de votre grille de consultation dans leur forme simple et robuste. Elle est découpée selon vos lettres."
T["scope_2"] = "Lot"
T["scope_3"] = "Ce qui est livré dans la V1"
T["scope_4"] = "<b>A. Mise en place et infrastructure</b>"
T["scope_5"] = "Serveur Hetzner (Allemagne), Docker, Dokploy, domaine, certificats SSL, environnements de test et de production séparés, sauvegardes automatisées quotidiennes, journalisation minimale des erreurs. Tous les comptes au nom du client."
T["scope_6"] = "<b>B. Intégration WhatsApp, deux numéros</b>"
T["scope_7"] = "360dialog sur la Cloud API de Meta : webhooks entrants, passerelle sortante, deux numéros configurés (voyageurs et fournisseurs), modèles interactifs avec boutons d'action rapide, routage par rôle, historique complet des messages."
T["scope_8"] = "<b>C. Moteur IA et orchestration</b>"
T["scope_9"] = "Couche d'abstraction multi-fournisseurs (Google, Anthropic, OpenAI, OpenRouter) commutable depuis le back-office sans redéploiement ; extraction structurée en français et en anglais ; une question ciblée lorsqu'une information essentielle manque ; tool calling (rechercher des fournisseurs, créer une demande, lire les réponses, mettre à jour le statut, escalader) ; formulation des offres à partir des données enregistrées uniquement ; prompts stockés, modifiables et historisés."
T["scope_10"] = "<b>D. Backend et modèle de données</b>"
T["scope_11"] = "PostgreSQL, API Node/TypeScript, la machine à états de la section 6, sollicitation semi-automatique des fournisseurs avec capture des réponses (boutons et texte libre horodatés), calcul indicatif des commissions, suivi des transactions sans flux bancaire."
T["scope_12"] = "<b>E. Back-office opérateur</b>"
T["scope_13"] = "Connexion sécurisée, gestion multi-opérateurs, flux des conversations en direct avec indicateur visuel clair IA/humain, reprise manuelle et restitution à l'IA, file « attention requise », liste des demandes par statut avec filtres, vue détaillée du client et historique, réponses des fournisseurs par demande, sélection manuelle des offres à présenter, ajout/modification/désactivation des fournisseurs et services sans toucher au code, modification du statut, panneau de configuration de l'IA (fournisseur, modèle, prompts)."
T["scope_14"] = "<b>F. Tracking QR et attribution</b>"
T["scope_15"] = "Identifiant unique par partenaire, URL courtes et codes QR différenciés, enregistrement du scan côté serveur avec anti-rebond, attribution de l'origine sur la fiche client, distinction entre partenaire d'origine et prescripteur de transaction dans le modèle de données, comptage des scans et conversations par partenaire."
T["scope_16"] = "<b>G. Livraison et courses</b>"
T["scope_17"] = "Catégorie coursiers dans le catalogue, sollicitation multi-coursiers en langage naturel, comparaison des devis et délais dans le back-office, sélection par l'opérateur, enregistrement des avances de fonds avec photo du justificatif, frais de service et statut de remboursement. Version simple et opérationnelle, sans routage géographique complexe."
T["scope_18"] = "<b>H. Tableau de bord KPI, exports, documentation et passation</b>"
T["scope_19"] = "Un tableau de bord dans le back-office affichant les métriques du pilote (scans, conversations, demandes, offres, réservations, abandons, temps de réponse par fournisseur, temps d'intervention humaine, panier moyen, attribution par partenaire) ; export CSV en un clic sur chaque liste principale (fournisseurs, clients, demandes, offres, réservations, transactions, partenaires) ; documentation d'installation, de déploiement, de configuration et d'exploitation ; inventaire des services tiers et coûts récurrents ; liste des composants open source et licences ; procédure de sauvegarde et restauration testée ; session de passation en direct de deux heures avec votre équipe."
T["scope_20"] = "7.1 Phase 2, après le pilote"
T["scope_21"] = "Les fonctionnalités ci-dessous sont volontairement placées après le pilote. Elles sont détachables, s'appuient sur les données que le pilote va accumuler, et les concevoir maintenant nécessiterait de deviner ce que les voyageurs et les fournisseurs font réellement :"
T["scope_22"] = "<b>Classement et sélection automatiques des fournisseurs :</b> un algorithme combinant prix, temps de réponse réel, taux d'acceptation, fiabilité et notation pour présélectionner les fournisseurs sans décision manuelle de l'opérateur."
T["scope_23"] = "<b>Relances automatisées :</b> relance d'un fournisseur sans réponse après dix minutes, relance d'un voyageur sans choix d'offre après une heure, alertes de l'opérateur lorsqu'une demande approche d'un seuil critique."
T["scope_24"] = "<b>Langues supplémentaires :</b> arabe, espagnol, allemand — ajoutées au moteur de dialogue et aux modèles de messages."
T["scope_25"] = "<b>Règles financières automatisées :</b> calcul et validation des reversements de commissions partenaires à partir des transactions terminées."
T["scope_26"] = "Tout ce qui ne figure ni dans la V1 ni dans la liste de phase 2 ci-dessus (application mobile, paiement en ligne centralisé, CRM marketing, scoring algorithmique avancé, identité de marque complète) est hors périmètre, conformément à la section 18 de votre cahier des charges."
T["scope_27"] = "Toute fonctionnalité hors périmètre fait l'objet d'un accord écrit et d'un chiffrage préalable."

# PLANNING (30 items)
T["planning_0"] = "Planning"
T["planning_1"] = "Huit semaines de la signature jusqu'au lancement du pilote en direct avec de vrais voyageurs. Un point hebdomadaire de trente minutes, et un accès permanent à l'environnement de staging pour que vous puissiez voir le produit prendre forme plutôt que d'attendre une démonstration."
T["planning_2"] = "Semaine"
T["planning_3"] = "Travaux"
T["planning_4"] = "Jalon"
T["planning_5"] = "<b>1</b>"
T["planning_6"] = "Infrastructure, base de données, modèle de données, machine à états ; onboarding 360dialog et vérification Meta lancés pour les deux numéros en parallèle (dépend de vos documents)"
T["planning_7"] = "Environnement de staging en ligne"
T["planning_8"] = "<b>2</b>"
T["planning_9"] = "Intégration WhatsApp côté voyageur, moteur IA multi-fournisseurs, extraction et création des demandes"
T["planning_10"] = "Premier dialogue voyageur devenant une demande structurée, sur un numéro de test"
T["planning_11"] = "<b>3</b>"
T["planning_12"] = "Numéro fournisseur et sollicitation (modèles, boutons, capture des réponses), offres renvoyées au voyageur"
T["planning_13"] = "Boucle complète opérationnelle sur les numéros de test, ouverte pour que vous l'utilisiez vous-même — <em>jalon de paiement 2</em>"
T["planning_14"] = "<b>4</b>"
T["planning_15"] = "Back-office : conversations, reprise humaine, demandes, fournisseurs, configuration de l'IA"
T["planning_16"] = "Vos opérateurs travaillent dans le back-office"
T["planning_17"] = "<b>5</b>"
T["planning_18"] = "Attribution QR, livraison et courses avec avances de fonds"
T["planning_19"] = "Demandes de courses traitées à travers plusieurs coursiers"
T["planning_20"] = "<b>6</b>"
T["planning_21"] = "Tableau de bord KPI, exports, sauvegardes et test de restauration"
T["planning_22"] = "Tests d'acceptation de la section 19 validés"
T["planning_23"] = "<b>7</b>"
T["planning_24"] = "Tests internes en conditions réelles, ajustement des prompts, corrections, chargement du catalogue fournisseurs et partenaires, documentation et session de passation"
T["planning_25"] = "Système accepté et documenté"
T["planning_26"] = "<b>8</b>"
T["planning_27"] = "Mise en production, premiers vrais voyageurs, surveillance rapprochée des premières conversations"
T["planning_28"] = "Pilote en direct — <em>jalon de paiement 3</em>"
T["planning_29"] = "<strong>Le seul élément hors de mon contrôle.</strong> La vérification d'entreprise Meta et l'approbation des modèles peuvent prendre quelques jours ou quelques semaines. Les deux numéros sont soumis en semaine 1 et le processus dépend des documents de votre société. Le développement se poursuit en parallèle sur des numéros de test, de sorte que cela ne retarde la mise en ligne que dans le pire des cas — mais c'est le seul point qui mérite de démarrer le jour où nous signons. Les jalons se décalent jour pour jour en cas de retard sur les documents, le catalogue ou les validations de votre côté."

print(f"Part 3 done: {len(T)} items.")
with open("scripts/i18n_data/part3.json", "w", encoding="utf-8") as f:
    json.dump(T, f, ensure_ascii=False, indent=2)
